In [16]:
import datetime

import pandas as pd

from db import get_connected

In [2]:
def establish_connection():
    try:
        conn=get_connected()
        return conn
    except Exception as e:
        print(e)

In [3]:
REFERENCE_WINDOW= 30

DRIFT_FEATURES = [
    "daily_return",
    "ma_7",
    "ma_21",
    "ma_ratio",
    "rsi",
    "volatility_7",
    "volume_change",
    "macd",
    "stochastic",
]

In [4]:
def get_data(conn) -> pd.DataFrame:

    cursor = conn.cursor()

    query="SELECT date,daily_return,ma_7,ma_21, ma_ratio, rsi,volatility_7,volume_change,macd,stochastic FROM features ORDER BY date"

    df=pd.read_sql(query,conn)

    return df

In [5]:
conn=establish_connection()
df=get_data(conn)

C:\Users\amito\AppData\Local\Temp\ipykernel_24304\926131288.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query,conn)

In [36]:
def separate_data(data:pd.DataFrame):

    cutoff_date= datetime.datetime.today() - datetime.timedelta(days=REFERENCE_WINDOW)

    current=data[data['date']>=cutoff_date]
    refrence= data[data['date']<cutoff_date]






    return current , refrence

In [37]:
current, refrence = separate_data(df)

In [38]:
current.head()

,date,daily_return,ma_7,ma_21,ma_ratio,rsi,volatility_7,volume_change,macd,stochastic
5630,2026-05-30,0.007504,83.240008,87.026414,0.956491,35.818424,0.008263,-0.324214,-1.422836,32.349534
5631,2026-05-30,0.005211,75013.629465,77393.266369,0.969253,28.756698,0.010855,-0.432247,-1032.098177,21.613039
5632,2026-05-30,0.117777,659.981794,658.968991,1.001537,69.210929,0.046840,1.920865,7.150325,91.590655
5633,2026-05-30,0.003718,2048.772879,2146.245629,0.954585,27.620227,0.011549,-0.499477,-66.143861,23.070796
5634,2026-05-31,-0.003016,82.818380,86.353620,0.959061,38.901097,0.008306,-0.022040,-1.465004,29.134606

In [40]:
refrence.tail()

,date,daily_return,ma_7,ma_21,ma_ratio,rsi,volatility_7,volume_change,macd,stochastic
5625,2026-05-29,0.002205,2062.557617,2160.877488,0.954500,23.193790,0.016426,-0.174968,-65.626555,17.338733
5626,2026-05-29,0.054451,423.391427,416.487418,1.016577,71.705490,0.023950,0.685790,6.037682,99.821138
5627,2026-05-29,0.007519,651.092634,655.721543,0.992941,35.218145,0.010986,-0.113835,1.849859,30.696725
5628,2026-05-29,-0.001440,308.544285,296.207464,1.041649,84.276757,0.005701,0.452224,10.452894,88.130790
5629,2026-05-29,-0.023700,229.859089,226.603795,1.014366,58.161174,0.012602,0.932007,-0.072407,41.347589